### ISSUE TITLE
error when starting noflo-nodejs

### ISSUE THREAD

**Issue by darrencruse** [razueroh/noflo-http#1]
new to noflo but was hoping to try it out for creating some REST apis that consume other such http/REST apis.

thought your module might help but just npm installing it (even with no usage of it in my graph) leads to the error: "instance.isLegacy is not a function"

jic it helps here's the entire output (so the error shown doesn't happen before installing noflo-http, does after installing, and goes away again after uninstalling):

```
$ npm install noflo-http --save
npm WARN deprecated coffee-script@1.10.0: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated core-js@1.2.7: core-js@<2.6.5 is no longer maintained. Please, upgrade to core-js@3 or at least to actual version of core-js@2.

+ noflo-http@0.1.2
updated 1 package and audited 1503 packages in 2.425s
found 32 vulnerabilities (7 low, 11 moderate, 14 high)
  run `npm audit fix` to fix them, or `npm audit` for details
$ ./node_modules/.bin/noflo-nodejs
NoFlo runtime is now listening at ws://164.144.164.107:3569
Browsers will reject connections from HTTPS pages to unsecured WebSockets
You can use insecure version of the IDE, or enable secure WebSockets with --tls-key and --tls-cert options
Live IDE URL: http://app.flowhub.io/#runtime/endpoint?protocol%3Dwebsocket%26address%3Dws%3A%2F%2F164.144.164.107%3A3569%26id%3De6b76b59-0864-4228-81c9-b0fe7a633a31%26secret%3DXXXXXXXX
instance.isLegacy is not a function
  at createComponent (/Users/dcrus/noflo-tests/noflo-nodejs-project/node_modules/noflo/lib/ComponentLoader.js:150:20)
  at Object.exports.dynamicLoad (/Users/dcrus/noflo-tests/noflo-nodejs-project/node_modules/noflo/lib/loader/NodeJs.js:199:10)
  at ComponentLoader.createComponent (/Users/dcrus/noflo-tests/noflo-nodejs-project/node_modules/noflo/lib/ComponentLoader.js:168:24)
  at ComponentLoader.load (/Users/dcrus/noflo-tests/noflo-nodejs-project/node_modules/noflo/lib/ComponentLoader.js:136:17)
  at ComponentProtocol.processComponent (/Users/dcrus/noflo-tests/noflo-nodejs-project/node_modules/noflo-runtime-base/protocol/Component.js:115:21)
  at componentNames.forEach (/Users/dcrus/noflo-tests/noflo-nodejs-project/node_modules/noflo-runtime-base/protocol/Component.js:55:23)
  at Array.forEach (<anonymous>:null:null)
  at loader.listComponents (/Users/dcrus/noflo-tests/noflo-nodejs-project/node_modules/noflo-runtime-base/protocol/Component.js:54:31)
    ...
$
```

**Comment by razueroh** [comment]
Hi @darrencruse I'm going to take a look into the issue. I think the problem is that the component use an older API and the new components must use the Process API. 

I haven't worked in those components for a long time so I can't promise it will be fixed fast, but I'll do my best. Can you give more info in order to replicate the issue, like the node version and noflo version you're using in your project?
